### PR TITLE
Migrate Terraform to 0.13, DataDog to 2.13

### PR DESCRIPTION
**Pull request by laurentr**

### CODE REVIEW

**Comment by houqp** [comment]
This introduced a major breaking change that will force all users into 0.13 so we need to be careful here. @laurentr shouldn't this work for both 0.12 and 0.13?

Also, would be nice to mention why we are upgrading to Datadog `2.13` as well.

**Comment by laurentr** [comment]
> This introduced a major breaking change that will force all users into 0.13 so we need to be careful here. @laurentr shouldn't this work for both 0.12 and 0.13?

I'm following the convention I've seen in most upstream modules that migrate to 0.13 I haven't seen any attempt to maintain compatibility with 0.12, but I'm happy to adjust. Are you suggesting ">= 0.12, < 0.14" ? I thought 0.12 doesn't read the 0.13 versions.tf 

> Also, would be nice to mention why we are upgrading to Datadog `2.13` as well.
I feel it's best to be on latest stable version of everything, but if you like older versions, I can revert.

**Comment by houqp** [comment]
Yes, I think it would be best to change it to ">= 0.12, < 0.14" unless there is 0.12 incompatible changes.

I am cool with upgrading to datadog 2.13 as well but looks like breaking changes were introduced in both version 2.13 and 2.12. Could you also change the version constraint to `>= 2.10, < 3`?

**Comment by jim80net** [comment]
Hi Y'all, 

I believe our friend @mpuri-tyl resolved this in https://github.com/scribd/terraform-aws-datadog/pull/21. 

Please reopen if we've left anything still tangled. 

Thank you!

**Comment by laurentr** [comment]
Looks good, thanks.

**Comment by jim80net** [comment]
HI @laurentr,  I wanted to let you know that we've moved terraform 0.13 compatibility from v1.3.4 to v2.0.0, since the changes ended up breaking older 0.12.x terraforms. 

When you have a chance to, please update your module to v2.0.0 =)

Thank you!

**Pull request closed without merging**
